# Generated by Django 2.1.4 on 2020-06-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
