version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abc
  backend:
    build:
      context: webapp/
      dockerfile: backend.dockerfile
    command: ./init.sh
    environment:
      DBHOST: mydb
      DBPASS: pass
      DBUSER: postgres
      DBNAME: abc
    volumes:
      - ./webapp/:/app
    ports:
      - "8000:8000"
    depends_on:
      - mydb
  task:
    build:
      context: .
      dockerfile: task.dockerfile
    command: ./init.sh
    environment:
      BACKEND_IP: backend
      BACKEND_PORT: 8000
      DBHOST: mydb
      DBPASS: pass
      DBUSER: postgres
      DBNAME: abc
    depends_on:
      - mydb

